get private conversation
codilingus/group-chat-backend pull request #23
Opened 2018-06-22 17:42 UTC by alekott

2018-06-22 17:48 UTC, e-stoj approved these changes

2018-06-22 17:54 UTC, e-stoj commented on src/main/java/com/example/chat/groupchatbackend/Conversation.java
> +    public boolean checkUser(User user){
non desriptive name

2018-06-23 06:21 UTC, michal-marciniec requested changes

2018-06-23 06:21 UTC, michal-marciniec commented on src/main/java/com/example/chat/groupchatbackend/Conversation.java
> +        for (User currentUser : getUsers()){
replace for -> stream and use `anyMatch` method

2018-06-23 06:21 UTC, michal-marciniec commented on src/main/java/com/example/chat/groupchatbackend/controllers/MessagesController.java
> +    public List <Message> getPrivateConversationMessagesWithUser(@PathVariable int conversationId, @RequestParam(required = false) Long timestamp) {
Hmmm.... we will need to refactor this one later 😛

2018-06-23 06:53 UTC, michal-marciniec approved these changes
Please merge fresh master. then ready to go

2018-06-23 06:56 UTC, merged